### ISSUE TITLE
TypeError: Deno.stdout.isTerminal is not a function

### ISSUE THREAD

**Issue by lviggiani** [deno-library/logger#16]
With Deno 1.39.2, by executing this in VS Code...
```typescript
import Logger from "https://deno.land/x/logger@v1.1.6/logger.ts";
const logger = new Logger();
```

I get this error:

```
error: Uncaught (in promise) TypeError: Deno.stdout.isTerminal is not a function
const isTTY = Deno.stdout.isTerminal();
                          ^
    at https://deno.land/x/logger@v1.1.6/stdout.ts:1:27
```

Am I doing anything wrong?

**Comment by fuxingZhang** [comment]
@UrielCh could you please take a look at and address this issue

**Comment by UrielCh** [comment]
Deno 1.39 is no more supported, update your deno runtime.

`deno upgrade`

or

`brew upgrade` for mac + brew.

**Comment by lviggiani** [comment]
Thanks. Unfortunately for the moment I cannot upgrade due to a project requirement.
