### ISSUE TITLE
增加中文文档

### ISSUE THREAD

**Issue by lpjia** [deno-library/logger#2]
为啥不加个中文文档, 也不麻烦, 对英文差的国人友好一点吧

**Comment by fuxingZhang** [comment]
deno使用的人少，很多喜欢js的还是坚持nodejs。自己写的使用人数微乎其微。
我已经转向golang开发2年了，已经没有精力维护之前nodejs和deno的库了。
目前就是有人提issue、pull request会处理一下。
我倒是期望有人来完善，文档、代码。
