### ISSUE TITLE
improve usage with dnt.

### ISSUE THREAD

**Issue by UrielCh** [deno-library/logger#5]
Hi,

There is 3 way to publish on npmjs a project using `https://deno.land/x/logger@v1.1.0/logger.ts`:
- do nothing, the hole code will be export and duplicated in the npm modules.
- replace on `https://deno.land/x/logger@v1.1.0/logger.ts` by an actual existing npm logger having the same interface, I did not find one yet. you are exporting a default class to build your logger.
- publish your logger to npm using [dnt](https://deno.com/manual@v1.33.1/advanced/publishing/dnt).

for now I'm using the first option.
do you known an existing npm module that match you interface ? I already check `winston`, `bunyan`, `pino`, `loglevel`, `npmlog`
would you like to publish your logger to npm? I can help you with that.

**Comment by fuxingZhang** [comment]
Since I haven't done JS and TS related development for years, can you help me do it.

**Comment by fuxingZhang** [comment]
![image](https://user-images.githubusercontent.com/25921552/236389275-d19b879c-8c4a-4194-a69d-0a86641318eb.png)

I have given you **maintain** permissions so that you can optimize and improve the repository.

**Thanks!**

**Comment by UrielCh** [comment]
adding dnt is the easy part, choosing the way it will be publishing is a bit more complicated...
the simplest way is to open a new organization in npm, and publish the project inside,

what is your npmjs username so IU can add you to the Organizations

**Comment by fuxingZhang** [comment]
> adding dnt is the easy part, choosing the way it will be publishing is a bit more complicated... the simplest way is to open a new organization in npm, and publish the project inside,
> 
> what is your npmjs username so IU can add you to the Organizations

My nmpjs username is "fuxingzhang"

**Comment by UrielCh** [comment]
invite  sent.

**Comment by fuxingZhang** [comment]
> invite  sent.

Done

**Comment by UrielCh** [comment]
all done.
